### ISSUE TITLE
Feature Request: Auto Worker Fail Open

### ISSUE THREAD

**Issue by loukaniko85** [crowdsecurity/cs-cloudflare-worker-bouncer#43]
Unless I have missed something, manual intervention is required every time the container is created to edit route created to fail open. Any way to automatic this as part of the container config?

Thanks

**Comment by LaurenceJJones** [comment]
> Unless I have missed something, manual intervention is required every time the container is created to edit route created to fail open. Any way to automatic this as part of the container config?

as per as documentation cloudflare does not expose this option via the api

```
The Remediation Component creates worker routes to make the workers act as a reverse proxy for your origin servers. The worker routes are created with the failover mode set to Fail Closed. There's no public Cloudflare API we can use to change/update it to Fail Open mode.
```

https://docs.crowdsec.net/u/bouncers/cloudflare-workers#setting-up-the-worker-route-fail-mode
